<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VPSearchServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/VPSearchServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/VPSearchServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://inm381/vps">
    <import location="http://localhost:8888/axis2/services/VPSearchService?wsdl" namespace="http://inm381/vps"/>
    <plnk:partnerLinkType name="VPSearchServiceLinkType">
        <plnk:role name="VPSearchServiceRole" portType="ns:VPSearchServicePortType"/>
    </plnk:partnerLinkType>
</definitions>
